workflow: android: refactor

diff --git a/.github/workflows/build_android.yml b/.github/workflows/build_android.yml
--- a/.github/workflows/build_android.yml
+++ b/.github/workflows/build_android.yml
@@ -10,9 +10,7 @@ on:
         options:
           - "LineageOS"
           - "EvolutionX"
-          - "Matrixx"
           - "PixelOS"
-          - "RisingOS"
       removals:
         description: "Folders to be removed before syncing:"
         required: false
@@ -24,7 +22,7 @@ on:
         options:
           - "eqe"
       build:
-        description: "Type of build:"
+        description: "Build Type:"
         required: true
         default: "user"
         type: choice
@@ -34,33 +32,27 @@ on:
           - "user"
       clean:
         description: "Clean"
-        required: true
         default: false
         type: boolean
       release:
         description: "Release"
-        required: true
         default: false
         type: boolean
 
 jobs:
-  Start-Runner:
+  prepare:
+    name: Start Runner
     runs-on: ubuntu-latest
 
     steps:
       - name: Set up environment
         run: sudo apt update && sudo apt install -y tmux
 
-      - name: Configure the 'crave' environment
+      - name: Configure Crave
         run: |
-          echo "DCDEVSPACE status: ${DCDEVSPACE}"
-          if [[ $DCDEVSPACE == *1* ]]; then
-            echo 'No need to set up crave, we are already running in devspace!'
-          else
-            curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
-            sudo mv crave /usr/local/bin/crave
-            echo "$CRAVE_CONF" > ${HOME}/crave.conf
-          fi
+          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
+          sudo mv crave /usr/local/bin/crave
+          echo "$CRAVE_CONF" > ${HOME}/crave.conf
         env:
           CRAVE_CONF: ${{ secrets.CRAVE_CONF }}
 
@@ -84,85 +76,50 @@ jobs:
             echo "Runner Started"
           fi"
 
-  prepare:
-    name: Prepare for Building
-    runs-on: ubuntu-latest
-    steps:
-      - name: Set Project variables
-        id: proj-variables
-        run: |
-          case "${{ inputs.android }}" in
-            "LineageOS")
-              export PROJECTFOLDER="/crave-devspaces/LineageOS"
-              export PROJECTID="93"
-              export REPO_URL="https://github.com/LineageOS/android.git"
-              export REPO_BRANCH="lineage-22.2"
-            ;;
-            "EvolutionX")
-              export PROJECTFOLDER="/crave-devspaces/EvolutionX"
-              export PROJECTID="93"
-              export REPO_URL="https://github.com/Evolution-X/manifest.git"
-              export REPO_BRANCH="bka"
-            ;;
-            "Matrixx")
-              export PROJECTFOLDER="/crave-devspaces/Matrixx"
-              export PROJECTID="93"
-              export REPO_URL="https://github.com/ProjectMatrixx/android.git"
-              export REPO_BRANCH="15.0"
-            ;;
-            "PixelOS")
-              export PROJECTFOLDER="/crave-devspaces/PixelOS"
-              export PROJECTID="93"
-              export REPO_URL="https://github.com/PixelOS-AOSP/manifest.git"
-              export REPO_BRANCH="fifteen"
-            ;;
-            "RisingOS")
-              export PROJECTFOLDER="/crave-devspaces/RisingOS"
-              export PROJECTID="93"
-              export REPO_URL="https://github.com/RisingOS-Revived/android.git"
-              export REPO_BRANCH="qpr2"
-            ;;
-          esac
-
-          echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_OUTPUT"
-          echo "PROJECTID=$PROJECTID"  >> "$GITHUB_OUTPUT"
-          echo "REPO_INIT=repo init --depth 1 --git-lfs -u $REPO_URL -b $REPO_BRANCH" >> "$GITHUB_OUTPUT"
-
-    outputs:
-      PROJECTFOLDER: ${{ steps.proj-variables.outputs.PROJECTFOLDER }}
-      PROJECTID: ${{ steps.proj-variables.outputs.PROJECTID }}
-      REPO_INIT: ${{ steps.proj-variables.outputs.REPO_INIT }}
-
   build:
     timeout-minutes: 1440
     name: Build using Crave
     runs-on: self-hosted
-    needs: [Start-Runner, prepare]
+    needs: prepare
     concurrency:
       group: ${{ github.repository_owner }}
+
     steps:
-      - name: Set Repo Project
+      - name: Set Project variables
         run: |
-          echo "PROJECTFOLDER=${{ needs.prepare.outputs.PROJECTFOLDER }}" >> "$GITHUB_ENV"
-          echo "PROJECTID=${{ needs.prepare.outputs.PROJECTID }}"  >> "$GITHUB_ENV"
+          target="bacon"
+
+          case "${{ inputs.android }}" in
+            "LineageOS")
+              manifest="https://github.com/LineageOS/android.git"
+              branch="lineage-22.2"
+            ;;
+            "EvolutionX")
+              manifest="https://github.com/Evolution-X/manifest.git"
+              branch="bka"
+              target="evolution"
+            ;;
+            "PixelOS")
+              manifest="https://github.com/PixelOS-AOSP/manifest.git"
+              branch="fifteen"
+            ;;
+          esac
+
+          echo "project=/crave-devspaces/${{ inputs.android }}" >> "$GITHUB_ENV"
+          echo "manifest=${manifest}" >> "$GITHUB_ENV"
+          echo "branch=${branch}" >> "$GITHUB_ENV"
+          echo "target=${target}" >> "$GITHUB_ENV"
 
       - name: Setup Project
         run: |
-          echo "DCDEVSPACE status: $DCDEVSPACE"
-          if [[ $DCDEVSPACE == *1* ]]; then
-            echo "We are in devspace."
-            echo $CRAVE_CONF > $HOME/crave.conf
-            crave clone create --projectID $PROJECTID $PROJECTFOLDER || echo "Crave clone create failed!"
-          else
-            echo "We are not in devspace, exiting..."
-            exit 1
-          fi
+          echo $CRAVE_CONF > $HOME/crave.conf
+          crave clone create --projectID 93 ${{ env.project }} || echo "Crave clone create failed!"
         env:
           CRAVE_CONF: ${{ secrets.CRAVE_CONF }}
 
       - name: Setup crave.yaml
         run: |
-          cat << EOF > $PROJECTFOLDER/.repo/manifests/crave.yaml
+          cat << EOF > ${{ env.project }}/.repo/manifests/crave.yaml
           LOS 22.1:
             ignoreClientHostname: true
             no-patch: true
@@ -170,70 +127,52 @@ jobs:
               GH_TOKEN: "${{ secrets.GH_TOKEN }}"
           EOF
 
-      - name: Set-up 'git' credential(s)
+      - name: Start compilation through Crave
         run: |
-          git config --global user.name "${{ github.actor }}"
-          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-
-      - name: Start compilation through 'crave'
-        run: |
-          cd $PROJECTFOLDER
-
-          echo "Build is queued! Please wait for your build to start."
-          echo "Check foss.crave.io Dashboard to see builds"
-          echo "Running build's log will show up here!"
+          cd ${{ env.project }}
 
           crave run --no-patch -- '# Run ID: ${{ github.run_id }}
           build_utils="https://raw.githubusercontent.com/SomeEmptyBox/android_build_utils/refs/heads/main"
 
           rm -rf .repo/local_manifests {device,vendor,kernel,hardware}/{motorola,private} ${{ inputs.removals }}
-          ${{ needs.prepare.outputs.REPO_INIT }}
+          repo init --depth 1 --git-lfs -u ${{ env.manifest }} -b ${{ env.branch }}
           curl -fLSs --create-dirs ${build_utils}/manifests/${{ inputs.device }}.xml -o .repo/local_manifests/default.xml
           git clone https://${GH_TOKEN}@github.com/SomeEmptyBox/android_vendor_private_keys vendor/private/keys
           /opt/crave/resync.sh
 
           curl -fLSs ${build_utils}/patches/telephony.patch | patch -p1 --forward
-          curl -fLSs ${build_utils}/patches/kernel.patch | patch -p1 --forward
           curl -fLSs ${build_utils}/patches/${{ inputs.android }}.patch | patch -p1 --forward
 
           source build/envsetup.sh
-          brunch ${{ inputs.device }} ${{ inputs.build }}
+          breakfast ${{ inputs.device }} ${{ inputs.build }}
+          cmka ${{ env.target }}
           '
         timeout-minutes: 1440
 
       - name: Pull ROM
         if: ${{ success() }}
         run: |
-          cd $PROJECTFOLDER
-          crave pull out/target/product/${{ inputs.device }}/{*.zip,eqe.json,boot.img,init_boot.img,vendor_boot.img,super_empty.img,recovery.img} -d ../artifacts/${{ inputs.android }}/${{ github.run_id }} || true
-          rm ../artifacts/${{ inputs.android }}/${{ github.run_id }}/*ota* || true
+          cd ${{ env.project }}
+          crave pull out/target/product/${{ inputs.device }}/{*.zip,boot.img,init_boot.img,vendor_boot.img,super_empty.img,recovery.img} -d ../builds/${{ inputs.android }}/${{ github.run_id }}
+          rm ../builds/${{ inputs.android }}/${{ github.run_id }}/*ota* || true
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@main
         with:
-          path: /crave-devspaces/artifacts/${{ inputs.android }}/${{ github.run_id }}
-
-      - name: Post Cleanup
-        if: ${{ always() }}
-        run: |
-          cd $PROJECTFOLDER
-          crave ssh -- '
-          source build/envsetup.sh
-          breakfast ${{ inputs.device }} ${{ inputs.build }}
-          mka installclean
-          '
+          name: ${{ inputs.android }}_${{ github.run_id }}
+          path: /crave-devspaces/builds/${{ inputs.android }}/${{ github.run_id }}
 
       - name: Execute if the job is cancelled
         if: ${{ cancelled() }}
         run: |
-          cd $PROJECTFOLDER
+          cd ${{ env.project }}
           crave stop --all
 
       - name: Display error.log
         if: ${{ failure() }}
         id: errorlog
         run: |
-          cd $PROJECTFOLDER
+          cd ${{ env.project }}
           crave ssh -- sleep 1
           crave pull out/error.log
           echo "Displaying out/error.log"
@@ -260,13 +199,12 @@ jobs:
           cat << EOF > release_notes.md
 
           Notes:
-           - Device: ${{ inputs.device }}
-           - Build Type: ${{ inputs.build }}
+          -> Device: ${{ inputs.device }}
+          -> Build Type: ${{ inputs.build }}
 
-          Sources:
-           - [Device](https://github.com/SomeEmptyBox/android_device_motorola_eqe/tree/${{ inputs.android }})
-           - [Vendor](https://gitlab.com/moto-sm7550/proprietary_vendor_motorola_eqe/tree/lineage-22.2)
-           - [Kernel](https://github.com/moto-sm7550-devs/android_kernel_motorola_sm7550/tree/lineage-22.1)
+          Links:
+          -> [Source](https://github.com/SomeEmptyBox/android_build_utils/blob/main/manifests/${{ inputs.device }}.xml)
+          -> [Download](https://nightly.link/SomeEmptyBox/android_build_utils/actions/runs/${{ github.run_id }}/${{ inputs.android }}_${{ github.run_id }}.zip)
           EOF
 
       - name: Create GitHub Release
